/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ctrmap.editor.gui.editors.gen5.battle.encounters;

import ctrmap.formats.pokemon.gen5.battle.encounters.WBEncEntry;
import ctrmap.formats.pokemon.text.TextFile;
import java.awt.event.ActionEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.event.ChangeEvent;

/**
 *
 * @author platinum
 */
public class VWildEncounterSlot extends javax.swing.JPanel {
    public VWildEncounterSlot() {
        initComponents();
    }
    
    public VWildEncounterSlot(WBEncEntry Entry, TextFile PkmnNames) {
        this();
        // Populate combobox for species.
        this.speciesComboBox.setModel(new DefaultComboBoxModel(PkmnNames.getFriendlyLinesArray()));
        this.speciesComboBox.addActionListener((ActionEvent ae) -> {
            short SelIndex = (short) this.speciesComboBox.getSelectedIndex();
            if (Entry != null && SelIndex >= 0) {
                Entry.SetDexNum(SelIndex);
            }
        });
        this.formSpinner.addChangeListener((ChangeEvent c) -> {
            short SelVal = (short) this.formSpinner.getValue();
            if (Entry != null && SelVal >= 0) {
                Entry.SetFormNum(SelVal);
            }
        });
        this.minLevelSpinner.addChangeListener((ChangeEvent c) -> {
            byte SelVal = (byte) this.minLevelSpinner.getValue();
            if (Entry != null && SelVal >= 0) {
                Entry.SetMinLevel(SelVal);
            }
        });
        this.maxLevelSpinner.addChangeListener((ChangeEvent c) -> {
            byte SelVal = (byte) this.maxLevelSpinner.getValue();
            if (Entry != null && SelVal >= 0) {
                Entry.SetMaxLevel(SelVal);
            }
        });
        UI_Update(Entry);
    }
    void UI_Update(WBEncEntry Entry) {
        if (Entry != null) {
            this.speciesComboBox.setSelectedIndex(Entry.GetDexNum());
            this.formSpinner.setValue(Entry.GetFormNum());
            this.minLevelSpinner.setValue((byte)Entry.GetMinLevel());
            this.maxLevelSpinner.setValue((byte)Entry.GetMaxLevel());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chancePercentageLabel = new javax.swing.JLabel();
        speciesComboBox = new javax.swing.JComboBox<>();
        formSpinner = new javax.swing.JSpinner();
        minLevelSpinner = new javax.swing.JSpinner();
        maxLevelSpinner = new javax.swing.JSpinner();

        chancePercentageLabel.setText("jLabel1");

        speciesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        formSpinner.setModel(new javax.swing.SpinnerNumberModel((short)0, null, null, (short)1));

        minLevelSpinner.setModel(new javax.swing.SpinnerNumberModel((byte)0, null, null, (byte)1));

        maxLevelSpinner.setModel(new javax.swing.SpinnerNumberModel((byte)0, null, null, (byte)1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chancePercentageLabel)
                .addGap(18, 18, 18)
                .addComponent(speciesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(minLevelSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maxLevelSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chancePercentageLabel)
                    .addComponent(speciesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minLevelSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxLevelSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chancePercentageLabel;
    private javax.swing.JSpinner formSpinner;
    private javax.swing.JSpinner maxLevelSpinner;
    private javax.swing.JSpinner minLevelSpinner;
    private javax.swing.JComboBox<String> speciesComboBox;
    // End of variables declaration//GEN-END:variables
}
